name: Angular Build

# {1}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Angular
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: front
      - name: Run tests
        run: npm run test  -- --browsers=ChromeHeadlessNoSandbox
        working-directory: front
        
      - name: Upload Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report                     # Set ID reference for step
        with:
          artifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: front/coverage/bobapp/index.html                     # Path to test results (inside artifact .zip)
          reporter: html            # Format of test results

  java:
    name: Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install dependencies
        run: mvn clean install
        working-directory: back

      - name: Run tests
        run: mvn test
        working-directory: back

      - name: Generate Jacoco report
        run: mvn jacoco:report
        working-directory: back

      - name: Upload Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report                     # Set ID reference for step
        with:
          artifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: back/target/site/jacoco/index.html                     # Path to test results (inside artifact .zip)
          reporter: html
