name: Angular / Java tests

on:
  workflow_call:

jobs:
  angular:
    name: Angular
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: front

      - name: Run tests
        run: npm run test  -- --browsers=ChromeHeadlessNoSandbox
        working-directory: front

      - name: Upload Kamra report
        uses: actions/upload-artifact@v3
        with:
          name: karma-report
          path: front/coverage/bobapp

  java:
    name: Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install dependencies
        run: mvn clean install
        working-directory: back

      - name: Run tests
        run: mvn test
        working-directory: back

      - name: Generate Jacoco report
        run: mvn jacoco:report
        working-directory: back

      - name: Upload Jacoco report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: back/target/site/jacoco
